// <auto-generated />
namespace BookShopWithAuthen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeField));
        
        string IMigrationMetadata.Id
        {
            get { return "201810110139485_changeField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
